### ISSUE TITLE
Package

### ISSUE THREAD

**Issue by llrs** [danasilv/ModulOmics#2]
Hi,

I have seen the [preprint](https://www.biorxiv.org/content/early/2018/03/24/288399) of the article that send me here. It seems interesting and it could be applied to other data types. Is the code planned to be released as a package?

**Comment by csimona** [comment]
Hi, due to the fact that ModulOmics needs CPLEX to run (which is a commercial software), we cannot wrap it as a single package. But, given that you have CPLEX, you can install everything via the snakefile. Also, have you tried the webserver? http://anat.cs.tau.ac.il/ModulOmicsServer/

**Comment by llrs** [comment]
Oh, I don't have CPLEX I didn't notice that system dependency. 
I am more interested on the statistical part rather than the data or the application on cancer. But seeing these dependencies I don't think I can use it.
